export DBAAS_MONGODB_ENDPOINT=m[mongo_dbaas_endpoint]
export DBAAS_MONGODB_PASSWORD=[mongo_dbaas_passwd]
export DBAAS_MONGODB_USER=[mongo_dbaas_user]
export EXTRA_MOUNT_COMMAND="ifconfig eth0 mtu 1332 &&"
export MONGODB_DB=[mongo_db]
export MONGODB_HOST=[mongo_host]
export MONGODB_PWD=[mongo_passwd]
export MONGODB_USER=[mongo_user]
export TAG_BACKUP_DBAAS=[tag_backup]
export WORKERS=5